apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: {{ $.Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ $.Values.image }}
              imagePullPolicy: Always
              env:
                - name: SOURCE_USER
                  value: {{ $.Values.sourceUser }}
                - name: DESTINATION_REMOTE
                  value: {{ $.Values.destinationRemote }}
                - name: GIT_AUTHOR_NAME
                  value: {{ $.Values.gitAuthorName }}
                - name: GIT_AUTHOR_EMAIL
                  value: {{ $.Values.gitAuthorEmail }}
                - name: DESTINATION_BRANCH
                  value: {{ $.Values.destinationBranch }}
                - name: DEPLOY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Chart.Name }}
                      key: deploy-key
          restartPolicy: OnFailure
