apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.secrets.config }}
      name: deploy-key
      property: projects.gitActivitySync.deployKey
