apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: git-activity-sync
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.secrets.config }}
      name: deploy-key
      property: deployKey
