name: ci

on: 
  push:
      branches:    
          - main

jobs:
  build:
    name: Build and Push to GitHub Registry
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        target: prod
        tags: ghcr.io/tim-ings/git-activity-sync:latest
